config/routes.rb
Reservation::Application.routes.draw do
  resources :reserves

  resources :clients

  resources :movies

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :reserves
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reserves
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  belongs_to :client
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reserves }
    end
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
    @reserve = Reserve.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserve }
    end
  end

  # GET /reserves/new
  # GET /reserves/new.json
  def new
    @reserve = Reserve.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserve }
    end
  end

  # GET /reserves/1/edit
  def edit
    @reserve = Reserve.find(params[:id])
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserve = Reserve.new(params[:reserve])

    respond_to do |format|
      if @reserve.save
        format.html { redirect_to @reserve, notice: 'Reserve was successfully created.' }
        format.json { render json: @reserve, status: :created, location: @reserve }
      else
        format.html { render action: "new" }
        format.json { render json: @reserve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reserves/1
  # PUT /reserves/1.json
  def update
    @reserve = Reserve.find(params[:id])

    respond_to do |format|
      if @reserve.update_attributes(params[:reserve])
        format.html { redirect_to @reserve, notice: 'Reserve was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserve = Reserve.find(params[:id])
    @reserve.destroy

    respond_to do |format|
      format.html { redirect_to reserves_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.phone %></td>
    <td><%= client.address %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @client.address %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservation</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.name %></td>
    <td><%= movie.gender %></td>
    <td><%= movie.duration %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Gender:</b>
  <%= @movie.gender %>
</p>

<p>
  <b>Duration:</b>
  <%= @movie.duration %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reserves/_form.html.erb
<%= form_for(@reserve) do |f| %>
  <% if @reserve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserve.errors.count, "error") %> prohibited this reserve from being saved:</h2>

      <ul>
      <% @reserve.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie %><br />
    <%= f.select :movie_id, Movie.all.map { |movie| [movie.name, movie.id] } %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.select :client_id, Client.all.map { |client| [client.name, client.id] } %>
  </div>
  <div class="field">
    <%= f.label :obs %><br />
    <%= f.text_field :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserves/edit.html.erb
<h1>Editing reserf</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserve %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/index.html.erb
<h1>Listing reserves</h1>

<table>
  <tr>
    <th>Movie</th>
    <th>Client</th>
    <th>Obs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reserves.each do |reserve| %>
  <tr>
    <td><%= reserve.movie %></td>
    <td><%= reserve.client %></td>
    <td><%= reserve.obs %></td>
    <td><%= link_to 'Show', reserve %></td>
    <td><%= link_to 'Edit', edit_reserf_path(reserve) %></td>
    <td><%= link_to 'Destroy', reserve, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reserve', new_reserve_path %>

app/views/reserves/new.html.erb
<h1>New reserve</h1>

<%= render 'form' %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @reserve.movie %>
</p>

<p>
  <b>Client:</b>
  <%= @reserve.client %>
</p>

<p>
  <b>Obs:</b>
  <%= @reserve.obs %>
</p>


<%= link_to 'Edit', edit_reserf_path(@reserve) %> |
<%= link_to 'Back', reserves_path %>